# filepath: /home/konrad/konradhorber/memory-game/Dockerfile.dev
FROM node:22

WORKDIR /app

# Install dependencies and enable hot-reload with bind mounting modules.
COPY package.json package-lock.json ./
RUN npm ci

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]