services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: memory-game-dev
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - .:/app

  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: memory-game-test
    command: npm run test
    ports:
      - 3000:3000